# https://taskfile.dev

version: '3'
silent: true

# vars:
#   GREETING: Hello, World!
tasks:
  dev:
    desc: 'Dev Diver'
    deps:
      - dev-client
      - dev-pkg
    run: once
  dev-pkg:
    desc: 'Dev Server'
    dir: diver-pkg
    cmds:
      - ~/.air
  dev-client:
    desc: 'Dev Client'
    dir: diver-client
    cmds:
      - npm run dev
